previews:
  generation: automatic
services:
- type: worker
  name: adr test worker
  runtime: python
  buildCommand: 'true'
  startCommand: 'env && sleep infinity'
  envVars:
  - key: ADR_KV_CONN_STRING
    fromService:
      type: keyvalue
      name: adr test kv
      property: connectionString
- type: keyvalue
  name: adr test kv
  ipAllowList:
  - source: 0.0.0.0/0
